Controllers/ApplicantsController.cs
using AARP.Models;
using AARP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AARP.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ApplicantsController : Controller
    {
        public ActionResult Index(string order)
        {
            var jobApplicantService = new JobApplicationProvider();
            var reviewerResourceServuce = new ReviewerProvider();
            var results = jobApplicantService.GetList().OrderByDescending(m => m.AppliedAt)
                .Select(applicant => new ApplicantViewModel()
                {
                    Applicant = applicant,
                    Reviewer = applicant.ReviewerId.HasValue ? reviewerResourceServuce.Get(applicant.ReviewerId.Value) : null
                });

            return View(results);
        }

        [HttpPost]
        public ActionResult UpdateApplicants()
        {
            BackgroundJobsManager.RefreshAssignedApplicantsState();

            var message = new MessageViewModel()
            {
                Type = MessageType.Success,
                Title = "Success",
                Content = string.Format("All assigned applicants have beed updated at {0}", DateTime.Now),
            };
            TempData["Message"] = message;


            return RedirectToAction("Index");
        }
    }
}

Controllers/ConfigurationController.cs
using AARP.Models;
using AARP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AARP.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ConfigurationController : Controller
    {

        public ActionResult Index()
        {
            return View(new AppConfigurationsViewModel());
        }

        [HttpPost]
        public ActionResult Index(AppConfigurationsViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.SaveChanges();
                BackgroundJobsManager.Initialize();
                //TO DO: update background jobs here
                TempData["Message"] = new MessageViewModel()
                {
                    Type = MessageType.Success,
                    Title = "Success",
                    Content = string.Format("Your configuration has been updated at {0} UTC ... New changes will take effect in 1 min", DateTime.UtcNow),
                };

                return RedirectToAction("Index");
            }
            return View(vm);
        }
    }
}

Controllers/PositionTypeController.cs
using AARP.Models;
using AARP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AARP.Controllers
{
    [Authorize]
    public class PositionTypeController : Controller
    {
        public ActionResult Index()
        {
            var service = new JobPositionTypeProvider();
            return View(service.GetList());
        }

        [HttpPost]
        public ActionResult Create(JobPositionType jobCatg)
        {
            if (ModelState.IsValid)
            {
                var service = new JobPositionTypeProvider();
                var results = service.Add(jobCatg);
                return Json(results);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
        }

        public ActionResult Edit(int id)
        {
            var service = new JobPositionTypeProvider();
            var positionType = service.Get(id);
            if (positionType == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            return Json(positionType);
        }

        [HttpPost]
        public ActionResult Edit(JobPositionType jobCatg)
        {
            if (ModelState.IsValid)
            {
                var service = new JobPositionTypeProvider();
                var results = service.Update(jobCatg);
                return Json(results);
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var service = new JobPositionTypeProvider();
            service.Delete(id);
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
        }

        public ActionResult Get(int id)
        {
            var service = new JobPositionTypeProvider();
            var results = service.Get(id);
            if (results == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);

            return Json(results, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/ReviewerController.cs
using AARP.Infrashtructure.DI;
using AARP.Models;
using AARP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AARP.WebApi;

namespace AARP.Controllers
{
    [Authorize]
    public class ReviewerController : Controller
    {
        IWebApiClient greenHouseAPI = DiContainers.Global.Resolve<IWebApiClient>();
        Random random = new Random();

        public ActionResult Index()
        {
            var provider = new ReviewerProvider();
            return View(provider.GetList());
        }

        public ActionResult Create()
        {
            var provider = new ReviewerProvider();
            return View(new Reviewer());
        }

        [HttpPost]
        public ActionResult Create(Reviewer reviewer)
        {
            Random random = new Random();
            if (ModelState.IsValid)
            {
                var provider = new ReviewerProvider();
                reviewer.Id = provider.GetNextId();
                provider.Add(reviewer);
                return RedirectToAction("Index");
            }
            return View(reviewer);
        }

        public ActionResult Details(int id)
        {
            var service = new ReviewerProvider();
            var reviewer = service.Get(id);
            if (reviewer == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            else
                return View(reviewer);
        }

        public ActionResult Edit(int id)
        {
            var service = new ReviewerProvider();
            var reviewer = service.Get(id);
            if (reviewer == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            return View(reviewer);
        }

        [HttpPost]
        public ActionResult Edit(Reviewer reviewer)
        {
            if (ModelState.IsValid)
            {
                var service = new ReviewerProvider();
                service.Update(reviewer);
                var message = new MessageViewModel()
                {
                    Type = MessageType.Success,
                    Title = "Success",
                    Content = string.Format("Reviewer {0} ({1}) has been updated...", reviewer.Name, reviewer.Email),
                };
                TempData["Message"] = message;

                return RedirectToAction("Index");
            }
            return View(reviewer);
        }

        public ActionResult Delete(int id)
        {
            var service = new ReviewerProvider();
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult Delete(Reviewer reviewer)
        {
            var service = new ReviewerProvider();
                service.Delete(reviewer.Id);
                var message = new MessageViewModel()
                {
                    Type = MessageType.Warning,
                    Title = "Deleted",
                    Content = string.Format("A reviewer has been deleted...", reviewer.Name, reviewer.Email),
                };
                TempData["Message"] = message;
                return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult SyncData()
        {
            var count = 0;
            var reviewerProvider = new ReviewerProvider();
            var message = new MessageViewModel();
            var usersGreenhouse = greenHouseAPI.GetUsers();
            if (usersGreenhouse == null || usersGreenhouse.Count == 0)
            {
                message.Type = MessageType.Error;
                message.Title = "Not Found";
                message.Content = "There're not data found vie GreenHouse API ";
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }

            foreach (var user in usersGreenhouse)
            {
                var reviewer = reviewerProvider.Get(int.Parse(user.Id));
                if (reviewer != null)
                    continue;
                reviewer = new Reviewer()
                {
                    Id = int.Parse(user.Id),
                    Name = user.Name,
                    Email = string.Join(";", user.Emails),
                };
                reviewerProvider.Add(reviewer);
                count++;
            }

            if (count == 0)
            {
                message.Type = MessageType.Info;
                message.Title = "Finished";
                message.Content = string.Format("No more updates found...", count);
            }
            else
            {
                message.Type = MessageType.Success;
                message.Title = "Success";
                message.Content = string.Format("Added new {0} reviewer(s)...", count);
            }

            TempData["Message"] = message;

            return RedirectToAction("Index");
        }

        public ActionResult Get()
        {
            var service = new ReviewerProvider();
            return Json(service.GetList(), JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Scopic CV Review Automation</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")" >
                    <img src="~/Content/Images/scopic-logo-v2-min2.png"  style="max-height:50px">
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index","PositionType")">
                            <span class="glyphicon glyphicon-tags"></span> Position Types
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Reviewer")">
                            <span class="glyphicon glyphicon-user"></span> Reviewers
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Applicants")">
                            <span class="glyphicon glyphicon-inbox"></span> Applicants
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Configuration")">
                            <span class="glyphicon glyphicon-cog"></span> Configurations
                        </a>
                    </li>
                    <li>
                        <a href="~/hangfire">
                            <span class="glyphicon glyphicon-tasks"></span> Background Tasks
                        </a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Scopic CV Review Automation</p>
        </footer>*@
    </div>
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>